const AUTH_COMPANY_REQUEST = "AUTH_COMPANY_REQUEST";
//Company Actions
const AUTH_COMPANY = "AUTH_COMPANY";
const AUTH_COMPANY_SUCCESS = "AUTH_COMPANY_SUCCESS";
const AUTH_COMPANY_ERROR = "AUTH_COMPANY_ERROR";
const AUTH_COMPANY_RESET = "AUTH_COMPANY_RESET";
const RESET_SETTINGS = "RESET_SETTINGS";

const GET_STAFF = "GET_STAFF";
const GET_STAFF_SUCCESS = "GET_STAFF_SUCCESS";
const GET_STAFF_FAIL = "GET_STAFF_FAIL";

//Auth Actions
const STAFF_AUTH = "STAFF_AUTH";
const STAFF_AUTH_SUCCESS = "STAFF_AUTH_SUCCESS";
const AUTH = "AUTH";
const AUTH_SUCCESS = "AUTH_SUCCESS";
const AUTH_FAIL = "AUTH_FAIL";

//Settings Actions
const SET_LASTLOGGEDINUSER = "SET_LASTLOGGEDINUSER";
const LOGOUT_USER = "LOGOUT_USER";

//UI STATE
const APP_LOADING = "APP_LOADING";
const APP_LOADED = "APP_LOADED";
const APP_BOOKING = "APP_BOOKING";
const APP_BOOKED = "APP_BOOKED";

//INVOICE
const CLEAR_INVOICE = "CLEAR_INVOICE";
const CLEAR_INVOICE_SESSION = "CLEAR_INVOICE_SESSION";
const SET_SELECTED_ROOM = "SET_SELECTED_ROOM";
const SET_REMAINING_QUANTITY = "SET_REMAINING_QUANTITY";
const SET_SLOT_TIME = "SET_SLOT_TIME";
const CLEAR_SLOT_TIME = "CLEAR_SLOT_TIME";
const SET_RESERVATION_TYPE = "SET_RESERVATION_TYPE";
const SET_CUSTOMER = "SET_CUSTOMER";
const CLEAR_SELECTED_CUSTOMER = "CLEAR_SELECTED_CUSTOMER";
const SET_INVOICE_NUMBER = "SET_INVOICE_NUMBER";
const SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT";
const SET_ROOM_SELECTED_PRODUCT = "SET_ROOM_SELECTED_PRODUCT";
const CLEAR_SELECTED_PRODUCT = "CLEAR_SELECTED_PRODUCT";
const SET_PRODUCT_QUANTITY = "SET_PRODUCT_QUANTITY";
const SET_SELECTED_ADDONS = "SET_SELECTED_ADDONS";
const SET_SELECTED_MEMBERSHIP = "SET_SELECTED_MEMBERSHIP";
const CLEAR_SELECTED_ADDONS = "CLEAR_SELECTED_ADDONS";
const SET_SELECTED_PROMOCODE = "SET_SELECTED_PROMOCODE";
const SET_PAID = "SET_PAID";

//ROOMS
const GET_ROOMS = "GET_ROOMS";
const GET_ROOMS_SUCCESS = "GET_ROOMS_SUCCESS";
const GET_ROOMS_FAIL = "GET_ROOMS_FAIL";
const CLEAR_ROOMS = "CLEAR_ROOMS";

//CUSTOMERS
const GET_CUSTOMERS = "GET_CUSTOMERS";
const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS";
const GET_CUSTOMERS_FAIL = "GET_CUSTOMERS_FAIL";
const ADD_CUSTOMER = "ADD_CUSTOMER";
const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS";
const ADD_CUSTOMER_FAIL = "ADD_CUSTOMER_FAIL";
const CLEAR_CUSTOMER_POSTING = "CLEAR_CUSTOMER_POSTING";

//BOOKING
const GET_BOOKINGS = "GET_BOOKINGS";
const GET_BOOKINGS_SUCCESS = "GET_BOOKINGS_SUCCESS";
const GET_BOOKINGS_FAIL = "GET_BOOKINGS_FAIL";
const SET_ACTIVE_SLOTS = "SET_ACTIVE_SLOTS";
const POST_BOOKING = "POST_BOOKING";
const POST_BOOKING_SUCCESS = "POST_BOOKING_SUCCESS";
const POST_BOOKING_FAIL = "POST_BOOKING_FAIL";
const CLEAR_BOOKING_POSTING = "CLEAR_BOOKING_POSTING";
const UPDATE_BOOKING = "UPDATE_BOOKING";
const UPDATE_BOOKING_SUCCESS = "UPDATE_BOOKING_SUCCESS";
const UPDATE_BOOKING_FAIL = "UPDATE_BOOKING_FAIL";
const REFUND_BOOKING = "REFUND_BOOKING";
const GET_BOOKINGS_RANGE = "GET_BOOKINGS_RANGE";
const GET_BOOKINGS_CASHIN_SUCCESS = "GET_BOOKINGS_CASHIN_SUCCESS";
const GET_BOOKINGS_BOOKINGLIST_SUCCESS =
  "GET_BOOKINGS_BOOKINGLIST_SUCCESS";
const GET_BOOKINGS_ORDERS_SUCCESS = "GET_BOOKINGS_ORDERS_SUCCESS";
const GET_BOOKINGS_RANGE_FAIL = "GET_BOOKINGS_RANGE_FAIL";
const CLEAR_BOOKINGS_OF_RANGE = "CLEAR_BOOKINGS_OF_RANGE";
const GET_BOOKING = "GET_BOOKING";

//SESSIONS
const GET_SESSIONS = "GET_SESSIONS";
const GET_SESSIONS_SUCCESS = "GET_SESSIONS_SUCCESS";
const GET_SESSIONS_FAIL = "GET_SESSIONS_FAIL";

//PRODUCTS
const GET_PRODUCTS = "GET_PRODUCTS";
const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";
const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";

//ADDONS
const GET_ADDONS = "GET_ADDONS";
const GET_ADDONS_SUCCESS = "GET_ADDONS_SUCCESS";
const GET_ADDONS_FAIL = "GET_ADDONS_FAIL";
const CLEAR_ADDONS = "CLEAR_ADDONS";

//PROMOCODES
const GET_PROMOCODES = "GET_PROMOCODES";
const GET_PROMOCODES_SUCCESS = "GET_PROMOCODES_SUCCESS";
const GET_PROMOCODES_FAIL = "GET_PROMOCODES_FAIL";
const CLEAR_PROMOCODES = "CLEAR_PROMOCODES";

//SETTINGS
const SET_SERVER_IP = "SET_SERVER_IP";
const SET_PRINTER_IP = "SET_PRINTER_IP";
const SET_SELECTED_BRANCH = "SET_SELECTED_BRANCH";

//BRANCHES
const GET_BRANCHES = "GET_BRANCHES";
const GET_BRANCHES_SUCCESS = "GET_BRANCHES_SUCCESS";
const GET_BRANCHES_FAIL = "GET_BRANCHES_FAIL";

//MEMBERSHIPS
const GET_MEMBERSHIPS = "GET_MEMBERSHIPS";
const GET_MEMBERSHIPS_SUCCESS = "GET_MEMBERSHIPS_SUCCESS";
const GET_MEMBERSHIPS_FAIL = "GET_MEMBERSHIPS_FAIL";

// SHIFTS
const SET_SHIFT_MODAL_VISIBILITY = "SET_SHIFT_MODAL_VISIBILITY";
const SET_CURRENT_SHIFT = "SET_CURRENT_SHIFT";
const END_SHIFT = "END_SHIFT";
